dist: xenial
language: python
python: ['3.7']
addons:
  apt:
    packages:
    - pandoc

script:
- make fetchnotebooks html

deploy:
  skip_cleanup: true
  provider: script
  on:
    branch: master
    repo: GeoscienceAustralia/dea-docs
  script: |
      pip install awscli
      aws s3 sync --size-only --delete _build/html/ s3://docs.dea.ga.gov.au
      aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths '/*'
