dist: xenial
language: python
python: ['3.7']
addons:
  apt:
    packages: [ pandoc ]

script:
- make fetchnotebooks html

deploy:
  skip_cleanup: true
  provider: script
  on:
    branch: master
    repo: GeoscienceAustralia/dea-docs
  script: bash .deployment/deploy.sh

