dist: xenial
language: python
python:
  - '3.7'

addons:
  apt:
    packages:
      - pandoc

script:
  - make install-deps fetchnotebooks html

deploy:
  - provider: s3
    bucket: "docs.dea.ga.gov.au"
    region: "ap-southeast-2"
    local_dir: _build/html/
    skip_cleanup: true
    on:
      branch: develop
      repo: GeoscienceAustralia/dea-docs
